controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    pid_wheels_controller:
      type: pid_controller/PidController

    mirte_base_controller:
      type: clearpath_mecanum_drive_controller/MecanumDriveController
mirte_base_controller:
  ros__parameters:
    # hardware_parameters:
    # ticks: 1320
    use_stamped_vel: false
    reference_timeout: 0.25
    command_timeout: 0.25
    command_joint_names: ["pid_wheels_controller/left_front_wheel_joint", "pid_wheels_controller/left_rear_wheel_joint", "pid_wheels_controller/right_rear_wheel_joint", "pid_wheels_controller/right_front_wheel_joint"]
    state_joint_names: ["left_front_wheel_joint", "left_rear_wheel_joint", "right_rear_wheel_joint", "right_front_wheel_joint"]
    interface_name: velocity

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }

      wheels_radius: 0.051

        # Wheels kinematic parameters [m]: (from odometry.hpp)
        # lx and ly represent the distance from the robot's center to the wheels
        #  projected on the x and y axis with origin at robots center respectively,
        #  sum_of_robot_center_projection_on_X_Y_axis_ = lx+ly

      sum_of_robot_center_projection_on_X_Y_axis: 0.225 # 0.18/2+0.27/2 = 0.225
          # wheel_separation_x: 0.18
          # wheel_separation_y: 0.27


    base_frame_id: "base_link"

    odom_frame_id: "odom"

    enable_odom_tf: true

    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]

    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]



pid_wheels_controller:
  ros__parameters:
    command_interface: velocity

    reference_and_state_interfaces: ["velocity"]

    # reference_and_state_dof_names:
    dof_names:
      - left_front_wheel_joint
      - left_rear_wheel_joint
      - right_rear_wheel_joint
      - right_front_wheel_joint
    gains:
      left_front_wheel_joint: {p: 10.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      left_rear_wheel_joint: {p: 10.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      right_rear_wheel_joint: {p: 10.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      right_front_wheel_joint: {p: 10.0,i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
