mirte_telemetrix:
  ros__parameters:
    device:
      mirte:
        type: breadboard
        board: pico
        max_frequency: 100
    distance:
      left:
        name: left
        device: mirte
        pins:
          trigger: 7
          echo: 6
      right:
        name: right
        device: mirte
        pins:
          trigger: 9
          echo: 8
#    keypad:
#      yellow:
#        name: yellow
#        device: mirte
#        pins:
#          pin: GP28
#    intensity:
#      left:
#        name: left
#        device: mirte
#        pins:
#          analog: GP27
#          digital: GP17
#    oled:
#      left:
#        name: left
#        device: mirte
#        pins:
#          scl: 5
#          sda: 4
#    servo:
#      left:
#        name: left
#        device: mirte
#        pins:
#          pin: GP15
    motor:
      left:
        name: left
        device: mirte
        type: pp
        pins:
          p1: 18             # pin needs PWM
          p2: 19             # pin needs PWM
      right:
        name: right
        device: mirte
        type: pp
        pins:
          p1: 20            # pin needs PWM
          p2: 21            # pin needs PWM
