device:
  mirte:
    type: breadboard
    mcu: pico
    max_frequency: 50
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: GP9
      echo: GP8
  right:
    name: right
    device: mirte
    pins:
      trigger: GP7
      echo: GP6
#encoder:
#  left:
#    name: left
#    device: mirte
#    pins:
#      pin: GP14
#  right:
#    name: right
#    device: mirte
#    pins:
#      pin: GP15
intensity:
  left:
    name: left 
    device: mirte
    pins:
      analog: GP27
      digital: GP17
  right:
    name: right
    device: mirte
    pins:
      analog: GP26
      digital: GP16
#oled:
#  left:
#    name: left
#    device: mirte
#    pins:
#      sda: GP10
#      scl: GP11
#  right:
#    name: right
#    device: mirte
#    pins:
#      sda: GP4
#      scl: GP5
servo: 
  left:
    name: left
    device: mirte
    pins:
      pin: GP3
# Servo on GP2 doens't work with the v0.6 pcb, next version this should be fixed
#  right:
#    name: right
#    device: mirte
#    pins:
#      pin: GP2
# These servo's have the same pins as the ObjectDetectors. So as 
# soon as they are implemented, these should be commented out
  gripper:
    name: gripper
    device: mirte
    pins:
      pin: GP12
  arm:
    name: arm 
    device: mirte 
    pins:
      pin: GP13
keypad:
  yellow:
    name: yellow
    device: mirte
    pins:
      pin: GP28
motor:
  left:
    name: left
    device: mirte
    type: l9110s
    pins:
      1a: GP19
      1b: GP18      
  right:
    name: right
    device: mirte
    type: l9110s
    pins:
      1a: GP21
      1b: GP20
# These motors have the same pins as the line intensity sensors. So
# when uncommenting these, please comment the intensity sensors.
#  left2:
#    name: left2
#    device: mirte
#    type: l9110s
#    pins:
#      1a: GP26
#      1b: GP16
#  right2:
#    name: right2
#    device: mirte
#    type: l9110s
#    pins:
#      1a: GP27
#      1b: GP17
# TODO: add obstacle detection
