device:
  mirte:
    type: breadboard
    mcu: pico
    max_frequency: 100
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: 7
      echo: 6
motor:
  left:
    name: left
    device: mirte
    type: l9110s
    pins:
      1a: 18             # pin needs PWM
      1b: 19             # pin needs PWM
  right:
    name: right
    device: mirte
    type: l9110s
    pins:
      1a: 20            # pin needs PWM
      1b: 21            # pin needs PWM
