/**:
  ros__parameters:
   
    device:
      mirte:
        type: pcb
        version: 0.8
        board: pico
        max_frequency: 50
    distance:
      left:
        name: left
        device: mirte
        pins:
          trigger: GP9
          echo: GP8
      right:
        name: right
        device: mirte
        pins:
          trigger: GP7
          echo: GP6
   
    intensity:
      left:
        name: left
        device: mirte
        pins:
          analog: GP27
          digital: GP17
      right:
        name: right
        device: mirte
        pins:
          analog: GP26
          digital: GP16
    oled:
      left:
        name: left
        device: mirte
        pins:
          sda: GP10
          scl: GP11
      right:
        name: right
        device: mirte
        pins:
          sda: GP4
          scl: GP5
    servo:
      left:
        name: left
        device: mirte
        pins:
          pin: GP14
      right:
        name: right
        device: mirte
        pins:
          pin: GP15
      # These servo's have the same pins as the ObjectDetectors. So as
      # soon as they are implemented, these should be commented out
      gripper:
        name: gripper
        device: mirte
        pins:
          pin: GP12
      arm:
        name: arm
        device: mirte
        pins:
          pin: GP13
    keypad:
      yellow:
        name: yellow
        device: mirte
        pins:
          pin: GP28
    motor:
      left:
        name: left
        device: mirte
        type: pp
        pins:
          p1: GP18
          p2: GP19
      right:
        name: right
        device: mirte
        type: pp
        pins:
          p1: GP20
          p2: GP21
    oled:
      oled:
        device: mirte
        connector: I2C1
    # encoder:
    #   left:
    #     name: left
    #     device: mirte
    #     pins:
    #       A: 15
    #   right:
    #     name: right
    #     device: mirte
    #     pins:
    #       A: 17

        # type: SSD1306 # Optional must be 'SSD1306'
        # default_screen_script can be a path or package URI (pkg://PACKAGE_NAME/FOLEDRS) to a image or an executable script which provides text.
        # By default it points to "pkg://mirte_telemetrix_cpp/scripts/default_screen.sh"
        # default_screen_script: "/home/jap/mirte/mirte-oled-images/images/mirte_logo_inv.png"
    # color:
    #   color:
    #     connector: I2C2
